export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',

}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {    
    return (
        <html lang="en">
            <body><header
                style={{
                    backgroundColor: 'LightBlure',
                    padding: "lrem",
                }}
                >
                <p>Header</p>
                </header>
                {children}
                <footer

                    style={{
                        backgroundColor: 'LightGray',
                        padding: "1rem",
                    }}
                    >   
                    <p>Footer</p>
                    </footer>
                    ;
                
                </body>
        </html>
    )
}   